name = "beagile"
pages_build_output_dir = "dist"
compatibility_date = "2026-08-15"
compatibility_flags = ["nodejs_compat"]
migrations_dir = "migrations"

[[d1_databases]]
binding = "DB"
database_name = "beagile"
database_id = "b8860740-7a8c-47a6-b0f9-44a69326f635"
